/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#ifndef _FATTOREX_H_RPCGEN
#define _FATTOREX_H_RPCGEN

#include <rpc/rpc.h>


#ifdef __cplusplus
extern "C" {
#endif

#define MAXNOME 64
#define N 20
#define NGIUDICI 4

struct Candidato {
	char candidato[MAXNOME];
	char giudice[MAXNOME];
	char categoria;
	char nomeFile[MAXNOME];
	char fase;
	int voto;
};
typedef struct Candidato Candidato;

struct Input {
	char candidato[MAXNOME];
	char operazione[MAXNOME];
};
typedef struct Input Input;

struct Tabella {
	Candidato statistiche[N];
};
typedef struct Tabella Tabella;

struct StatisticaGiudice {
	char giudice[MAXNOME];
	int voto;
};
typedef struct StatisticaGiudice StatisticaGiudice;

struct Output {
	StatisticaGiudice punteggi[NGIUDICI];
};
typedef struct Output Output;

#define FATTOREX 0x20000013
#define FATTOREXVERS 1

#if defined(__STDC__) || defined(__cplusplus)
#define CLASSIFICA_GIUDICI 1
extern  Output * classifica_giudici_1(void *, CLIENT *);
extern  Output * classifica_giudici_1_svc(void *, struct svc_req *);
#define ESPRIMI_VOTO 2
extern  int * esprimi_voto_1(Input *, CLIENT *);
extern  int * esprimi_voto_1_svc(Input *, struct svc_req *);
extern int fattorex_1_freeresult (SVCXPRT *, xdrproc_t, caddr_t);

#else /* K&R C */
#define CLASSIFICA_GIUDICI 1
extern  Output * classifica_giudici_1();
extern  Output * classifica_giudici_1_svc();
#define ESPRIMI_VOTO 2
extern  int * esprimi_voto_1();
extern  int * esprimi_voto_1_svc();
extern int fattorex_1_freeresult ();
#endif /* K&R C */

/* the xdr functions */

#if defined(__STDC__) || defined(__cplusplus)
extern  bool_t xdr_Candidato (XDR *, Candidato*);
extern  bool_t xdr_Input (XDR *, Input*);
extern  bool_t xdr_Tabella (XDR *, Tabella*);
extern  bool_t xdr_StatisticaGiudice (XDR *, StatisticaGiudice*);
extern  bool_t xdr_Output (XDR *, Output*);

#else /* K&R C */
extern bool_t xdr_Candidato ();
extern bool_t xdr_Input ();
extern bool_t xdr_Tabella ();
extern bool_t xdr_StatisticaGiudice ();
extern bool_t xdr_Output ();

#endif /* K&R C */

#ifdef __cplusplus
}
#endif

#endif /* !_FATTOREX_H_RPCGEN */
